import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, MessageCircle, Sparkles } from 'lucide-react';
import { motion } from 'framer-motion';
import { api, business, whatsappUrl } from '../lib/api.js';
import ProductCard from '../components/ProductCard.jsx';

export default function Home(){
 const [products,setProducts]=useState([]);
 useEffect(()=>{api.get('/products?limit=8').then(r=>setProducts(r.data.products||[])).catch(()=>{});},[]);
 return <main>
  <section className="luxury-hero overflow-hidden text-white"><div className="section-shell grid min-h-[620px] items-center gap-12 py-16 lg:grid-cols-[1.1fr_.9fr] lg:py-24">
   <motion.div initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{duration:.7}}><p className="mb-5 inline-flex items-center gap-2 rounded-full border border-[#d7b87d]/30 px-4 py-2 text-xs font-bold uppercase tracking-[.2em] text-[#e2c68f]"><Sparkles size={14}/> Sumptuous Braids</p><h1 className="font-display text-5xl font-semibold leading-[1.02] sm:text-7xl">Beautiful hair.<br/><span className="text-[#d5ad68]">Beautifully done.</span></h1><p className="mt-6 max-w-xl text-base leading-8 text-stone-300 sm:text-lg">Professional braiding, hair care and branded products from a beauty business you can reach directly — without being sent from website to website.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/services" className="inline-flex items-center gap-2 rounded-full bg-[#d0a55f] px-6 py-3.5 font-bold text-black">Book a service <ArrowRight size={18}/></Link><Link to="/shop" className="rounded-full border border-white/20 px-6 py-3.5 font-bold">Shop products</Link><a href={whatsappUrl()} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full bg-[#168c43] px-6 py-3.5 font-bold"><MessageCircle size={18}/> Chat on WhatsApp</a></div></motion.div>
   <div className="relative mx-auto w-full max-w-md"><div className="aspect-[4/5] rounded-[2.5rem] border border-[#d7b87d]/25 bg-gradient-to-br from-[#3c2b1a] via-[#17130f] to-[#0b0a08] p-5 shadow-2xl"><div className="flex h-full items-end rounded-[2rem] border border-[#d7b87d]/15 p-7"><div><p className="text-xs uppercase tracking-[.3em] text-[#d5ad68]">86 Wethral Road · Owerri</p><h2 className="mt-3 font-display text-4xl">Your hair is our craft.</h2></div></div></div></div>
  </div></section>
  <section className="section-shell py-14"><div className="grid gap-4 md:grid-cols-3"><Feature title="Salon Services" text="Braids, installations and professional styling with a direct booking route." href="/services"/><Feature title="Branded Products" text="Hair oil, edge control, braiding extensions and future products in one shop." href="/shop"/><Feature title="Wholesale Supply" text="For salons, vendors and stores that want to stock Sumptuous Braids products." href="/wholesale"/></div></section>
  <section className="section-shell pb-16"><div className="mb-8 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.3em] text-[#a47638]">The collection</p><h2 className="font-display text-4xl">Featured products</h2></div><Link to="/shop" className="font-bold text-[#a47638]">View shop →</Link></div><div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">{products.map(p=><ProductCard key={p.id} product={p}/>)}</div>{!products.length&&<div className="rounded-3xl border border-dashed border-black/10 bg-white p-10 text-center text-stone-500">Products will appear here as they are added from the admin dashboard.</div>}</section>
  <section className="section-shell pb-16"><div className="rounded-[2rem] bg-[#15130f] p-8 text-white sm:p-12"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.3em] text-[#d5ad68]">Always reachable</p><h2 className="mt-3 font-display text-4xl">Need to ask something? Go straight to WhatsApp.</h2><p className="mt-3 max-w-2xl leading-7 text-stone-400">No hidden inbox. No complicated contact flow. Send a message directly to {business.phone}.</p></div><a href={whatsappUrl()} target="_blank" rel="noreferrer" className="rounded-full bg-[#168c43] px-7 py-4 text-center font-bold">Chat now</a></div></div></section>
 </main>
}
function Feature({title,text,href}){return <Link to={href} className="group rounded-3xl border border-black/5 bg-white p-7 card-shadow transition hover:-translate-y-1"><p className="text-xs font-bold uppercase tracking-[.25em] text-[#a47638]">Sumptuous</p><h3 className="mt-3 font-display text-2xl">{title}</h3><p className="mt-2 text-sm leading-6 text-stone-500">{text}</p><span className="mt-5 inline-block text-sm font-bold group-hover:text-[#a47638]">Explore →</span></Link>}
